### configuration for terraform-docs

formatter: "markdown" # not optionnal
version: ">=0.17, <1.0"

header-from: main.tf
#footer-from: ""

#recursive:
#  enabled: false
#  path: modules

#sections:
#  hide: []
#  show: []
# all, data-sources, header, footer, inputs, modules, outputs, providers, requirements, resources

#content: "" # to change the default template

output:
  file: "../README.md"
  mode: inject
  template: |-
    [//]: # (BEGIN_TF_DOCS)
    {{ .Content }}

    [//]: # (END_TF_DOCS)

# First generate output values file in JSON format: $ terraform output --json > output_values.json
# and then use the following to render them in the generated output:
#output-values:
#  enabled: false
#  from: ""

#sort:
#  enabled: true
#  by: name

settings:
#  anchor: true
#  color: true
#  default: true
  description: true
#  escape: true
#  hide-empty: false
#  html: true
#  indent: 2
#  lockfile: true
#  read-comments: true
#  required: true
#  sensitive: true
#  type: true

